name: Go CricHD Auto Update (M3U & JSON)

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Clone Private Repository
        run: |
          git clone https://${{ secrets.GH_PAT }}@github.com/srhady/Sports.git private_repo

      - name: Run Python Scraper
        run: |
          python private_repo/go_crichd_scraper.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # এখানে ফাইলের নামগুলো আপডেট করা হয়েছে
          git add Go_Live_Events.m3u Go_Live_Events.json
          
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-updated go.crichd.tv Live Events"
          git push
