name: Auto Update All Live Events (M3U & JSON)

on:
  workflow_dispatch:

jobs:
  update-playlists:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Clone Private Repository
        run: |
          git clone https://${{ secrets.GH_PAT }}@github.com/srhady/Sports.git private_repo

      - name: Run All Scrapers
        run: |
          python private_repo/crichd_event_scraper.py
          python private_repo/go_crichd_scraper.py
          python private_repo/footy.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add Live_Events.m3u Live_Events.json Go_Live_Events.m3u Go_Live_Events.json Footy_Live.m3u Footy_Live.json
          
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-updated All Live Events" && git pull --rebase origin main && git push)
